export const ADICIONA_PROJETO = "ADICIONA_PROJETO"
export const EDITA_PROJETO = "EDITA_PROJETO"
export const EXCLUI_PROJETO = "EXCLUI_PROJETO"
export const LISTA_PROJETOS = "LISTA_PROJETOS"

export const ADICIONA_TAREFA = "ADICIONA_TAREFA"
export const NOTIFICAR = "NOTIFICAR"
